# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 23:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20170521_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lft', models.PositiveIntegerField(
                    db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(
                    db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(
                    db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(
                    db_index=True, editable=False)),
                ('channel', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='category.Channel')),
                ('parent', mptt.fields.TreeForeignKey(
                    null=True, on_delete=django.db.models.deletion.CASCADE,
                    related_name='children', to='category.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
