# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 04:20
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='channel',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
