# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 23:40
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_auto_20170522_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE,
                related_name='category', to='category.Category'),
        ),
    ]
